### PR TITLE
Update to bootstrap v4 beta

### PR DESCRIPTION
**Pull request by benmccallum**
Upgrading to bootstrap v4 and handling all the annoyances and new
dependencies.
* Tether replaced with Popper.js
* Some renamed scss variables

Fixing what was likely a pre-existing issue I found with my own repo
whereby bootstrap scss was building, but not going through the right
webpack loader and plugins meaning that postcss processes like
autoprefixer weren't running. Picked up when looking at custom-select
and noticing with missing prefixes there were multiple icons for the
arrow/s.
* Fixed by editing the vue templated utils.js build file to output the right scss loaders config using a separated bootstrapUtil.js file to keep it clean.

### CODE REVIEW

**Comment by benmccallum** [comment]
Hey mate,

I found your guide pretty useful in my own project so as I was upgrading to the recently released beta I thought I'd upgrade your guide too.

I've covered all the things I think are most relevant, the only thing I might be missing is if you've used bootstrap components/classes/etc that need migration if they've changed. If you wanna sweep that and test your demo app then this is probably good to merge.

Cheers,
Ben

PS. vue-cli has updated their templates recently, including the one for webpack so I'll probably integrated those changes when I get a sec, as another PR.

**Comment by benmccallum** [comment]
Just added how to for favicon as well, seemed like it'd help people. Had to do some reading to find it.

**Comment by prograhammer** [comment]
Hey @benmccallum 

Wow, I'm very honored you took the time to submit a PR! But tomorrow I'm releasing a huge update to the whole guide and project. Plus putting it up live on GitHub pages! Get ready to check it out!

**Comment by benmccallum** [comment]
Oh man. That'll teach me to not check first. I had a feeling you might be and checked for another branch/recent commits but should've asked. Look forward to checking it out. Feel free to close.

**Comment by fyllepo** [comment]
@prograhammer this repo has been a big help to me in the past, looking forward to the update.

Thanks!

**Comment by benmccallum** [comment]
I guess I should close this PR? Updates are still valid for Bootstrap v4, so it could be useful to someone else.

**Pull request closed without merging**
